export const monthlyPlans = [
  {
    price_id: "price_1NjQBiSFbNWg0NYAiw2v9lbi",
    name: "mobile",
    price: 100,
    videoQuality: "good",
    resolution: "480p",
    devices: ["phone", "tablet"],
    billingCycle: "monthly",
    priceText: "100/mo",
  },
  {
    price_id: "price_1NjVLmSFbNWg0NYA3Lpcn8Vt",
    name: "basic",
    price: 200,
    videoQuality: "good",
    resolution: "480p",
    devices: ["phone", "tablet", "computer", "tv"],
    billingCycle: "monthly",
    priceText: "200/mo",
  },
  {
    price_id: "price_1NjVNRSFbNWg0NYA0RPf89oy",
    name: "standard",
    price: 500,
    videoQuality: "better",
    resolution: "1080p",
    devices: ["phone", "tablet", "computer", "tv"],
    billingCycle: "monthly",
    priceText: "500/mo",
  },
  {
    price_id: "price_1NjVOOSFbNWg0NYAaA8CFYvu",
    name: "premium",
    price: 700,
    videoQuality: "best",
    resolution: "4K+HDR",
    devices: ["phone", "tablet", "computer", "tv"],
    billingCycle: "monthly",
    priceText: "700/mo",
  },
];

export const yearlyPlans = [
  {
    price_id: "price_1NjTjCSFbNWg0NYAOCvJ0s8j",
    name: "mobile",
    price: 1000,
    videoQuality: "good",
    resolution: "480p",
    devices: ["phone", "tablet"],
    billingCycle: "yearly",
    priceText: "1000/yr",
  },
  {
    price_id: "price_1NjVLmSFbNWg0NYAMKWu0q3s",
    name: "basic",
    price: 2000,
    videoQuality: "good",
    resolution: "480p",
    devices: ["phone", "tablet", "computer", "tv"],
    billingCycle: "yearly",
    priceText: "2000/yr",
  },
  {
    price_id: "price_1NjVNRSFbNWg0NYAL74Pt3tz",
    name: "standard",
    price: 5000,
    videoQuality: "better",
    resolution: "1080p",
    devices: ["phone", "tablet", "computer", "tv"],
    billingCycle: "yearly",
    priceText: "5000/yr",
  },
  {
    price_id: "price_1NjVOOSFbNWg0NYAwAyvRtD3",
    name: "premium",
    price: 7000,
    videoQuality: "best",
    resolution: "4K+HDR",
    devices: ["phone", "tablet", "computer", "tv"],
    billingCycle: "yearly",
    priceText: "7000/yr",
  },
];
